# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Lesley Bell"
description: > # this means to ignore newlines until "email:"
   I'm a UX designer and developer based in the San Francisco Bay area.

email: lesley@lesleybell.com
#blog logo
logo: "https://cloud.githubusercontent.com/assets/5618996/4513019/415d9152-4b47-11e4-81e0-231335473c37.jpg"
# blog cover
cover: "https://cloud.githubusercontent.com/assets/5618996/4511514/891b2b9c-4b35-11e4-9e4d-6a3852dda0dd.jpg"

name: 'Lesley Bell'
author: 'Lesley Bell'
author_image: "https://cloud.githubusercontent.com/assets/5618996/4512726/ade16492-4b43-11e4-8763-00ddab1ed88e.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/lb2045
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tinkerb
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

 - icon:	google-plus
   url:	https://google.com/lbx2045
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
