---
# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Sargonas ://: J. Eckert"
description: > # this means to ignore newlines until "email:"
   Completely making it up as I go along

#email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: "J. 'Sargonas' Eckert"
author: "J. 'Sargonas' Eckert"
author_image: "/assets/images/author.jpg"

paginate: 10

url: "http://sargonas.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: "@sargonas"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/sargonas
    desc: Follow me on twitter
    #share_url: http://twitter.com/share
    #share_title: ?text=
    #share_link: "&amp;url="

#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: instagram
    url:  https://instagram.com/sargonas
    desc: I sometimes take pretty pictures
#    share_url:
#    share_title:
#    share_link:

  - icon: github
    url:  https://github.com/sargonas
    desc: Fork me on github
    share_url:
    share_title:
    share_link:
