# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
title: "Ben Brown"
description: > # this means to ignore newlines until "email:"
   PhD Student in Mathematics at The University of Edinburgh

url: http://bencwbrown.co.uk

email: b.c.w.brown@sms.ed.ac.uk
#blog logo
logo: "/assets/images/author.jpg"
logo2: "/assets/images/caps2017.jpg"
# blog cover
cover: "/assets/images/caps2017.jpg"
covercredits: "Kyaw Shaw & Feiyu Fang"

name: 'Benjamin C. W. Brown'
author: 'Ben Brown'
author_image: "/assets/images/author.jpg"

paginate:	10
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title

url: "https://www.bencwbrown.co.uk" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@bencwbrown'

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/benjamincwbrown
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:	facebook
    url:	https://www.facebook.com/TheNotoriousBB
    desc: Friend me on Facebook
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:	github
    url:	https://github.com/bencwbrown
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#   - icon:	google-plus
#     url:
#     desc:
#     share_url:
#     share_title:
#     share_link:

#  - icon: rss
#    url:  http://audreywatters.com/feed.xml
#    desc: Subscribe
#    share_url:
#    share_title:
#    share_link:

  - icon: envelope
    url:  mailto:b.c.w.brown@sms.ed.ac.uk
    desc: Email
    share_url:
    share_title:
    share_link:
