# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Intelligent Design"
description: > # this means to ignore newlines until "email:"
   Design is the act of creating intentionally.  

email: lesley@lesleybell.com
#blog logo
logo: "https://cloud.githubusercontent.com/assets/5618996/4511505/6fb039ae-4b35-11e4-9f78-9844f9e4e308.png"
# blog cover
cover: "https://cloud.githubusercontent.com/assets/5618996/4511514/891b2b9c-4b35-11e4-9e4d-6a3852dda0dd.jpg"

name: 'Lesley Bell'
author: 'Lesley Bell'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/lb2045
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
